- database/migrations/2023_11_02_021758_create_articles_table.php
- database/migrations/2023_11_02_030818_create_gallery_activities_table.php
- database/migrations/2023_11_02_032322_create_contact_menu_table.php
- database/migrations/2023_11_02_032849_create_divisions_table.php
- database/migrations/2023_11_02_033506_create_team_members_table.php
- database/migrations/2023_11_02_035113_create_categories_table.php
- database/migrations/2023_11_02_035405_create_portfolios_table.php
- database/migrations/2023_11_02_035722_create_portfolios_categories_table.php
- database/migrations/2023_11_02_040319_create_portfolio_images_table.php
Menambahkan migration : 
1. artikel
2. kategori
3. menu kontak
4. devisi 
5.  aktivitas galeri
6. migrasi
7. image portofolio
8. portofolio
9. kategori portofolio
11. member team
12. user
> feat: add all migrations

- resources/css/app.css
- tailwind.config.js
update colors and fonts setup for tailwind
> feat:add configurasion for colors and fonts

- app/Http/Controllers/DivisionController.php
- app/Http/Controllers/TeamMemberController.php
- app/Models/Division.php
- app/Models/TeamMember.php
- database/factories/DivisionFactory.php
- database/factories/TeamMemberFactory.php
menambahkan :
1. model
2. controller 
3. factory
untuk : 
- team member
- division
> feat: add model controller factory; teamMember-division

- app/Http/Controllers/ArticleController.php
- app/Models/Article.php
- database/factories/ArticleFactory.php
menambahkan :
1. model
2. controller
3. factory
pada article
> feat: add model controller factory; article

- app/Http/Controllers/ContactMenuController.php
- app/Http/Controllers/GalleryActivityController.php
- app/Models/ContactMenu.php
- app/Models/GalleryActivity.php
- database/factories/ContactMenuFactory.php
- database/factories/GalleryActivityFactory.php
menambahkan dan membuat : 
1. model 
2. controller 
3. factory
berisi gallery activity
> Feature/no ref/add model controller gallery activity

- app/Http/Controllers/ContactMenuController.php
- app/Models/ContactMenu.php
- database/factories/ContactMenuFactory.php
menambahkan  dan membuat : 
1. model
2. controller
3. factory
berisi contact menu
> feat: add model controller factory; contact menu

- database/migrations/2023_11_02_131439_create_category_portfolio_table.php
- database/seeders/DatabaseSeeder.php
add migration many-many of portfolios.
add factory seed for `categories`, `portfolios`, `portfolioImages` and `category_portfolio`
> refactor: add new migration of portfolio-categories table; add factory

- app/Http/Controllers/PortfolioController.php
- app/Http/Controllers/PortfoliosCategoryController.php
- app/Models/Category.php
- app/Models/CategoryPortfolio.php
- app/Models/Portfolio.php
- app/Models/PortfolioImage.php
- database/factories/CategoryFactory.php
- database/factories/PortfolioFactory.php
- database/factories/PortfolioImageFactory.php
- package-lock.json
membuat :
1. model
2. controller
3. factory
yang berisikan :  
1. category
2. portfolio
3. portfolio image
4. portfolio-category
> Feature/no ref/add model controller portfolio

- app/View/Components/AppLayout.php
- resources/views/components/app-layout.blade.php
menambahkan components dan blade untuk app layout
> feat:add view components app layout

- app/View/Components/AppLayout.php
- resources/views/components/app-layout.blade.php
- resources/views/components/navbar.blade.php
> Feature/no ref/add navbar component

- resources/views/welcome.blade.php
menambahkan gap dan titlle view welcome
> feat:add gap and titlle view welcome

- app/View/Components/Pages/TeamMember.php
- resources/views/components/member-card.blade.php
- resources/views/components/pages/team-member.blade.php
- routes/web.php
menambahkan fitur view dan route team member
> feat:add team member blade view

- database/factories/ContactMenuFactory.php
> refactor: image url factories contact menu

- database/factories/GalleryActivityFactory.php
> refactor: image url factories gallery activity

- app/View/Components/MemberCard.php
- app/View/Components/Pages/Gallery.php
- database/factories/PortfolioImageFactory.php
> refactor: image url factories portfolio

- app/Models/TeamMember.php
- database/factories/TeamMemberFactory.php
> refactor: image url factories team member

- app/View/Components/Pages/AboutUs.php
- database/factories/TeamMemberFactory.php
- resources/views/components/app-layout.blade.php
- resources/views/components/pages/about-us.blade.php
- resources/views/components/welcome.blade.php
- resources/views/welcome.blade.php
> Feature/no ref/add aboutus page

- app/View/Components/Category.php
- app/View/Components/ChooseBox.php
- app/View/Components/Pages/ListPortfolio.php
- app/View/Components/PortfolioCard.php
- resources/views/components/category.blade.php
- resources/views/components/choose-box.blade.php
- resources/views/components/navbar.blade.php
- resources/views/components/pages/list-portfolio.blade.php
- resources/views/components/portfolio-card.blade.php
- routes/web.php
menambahkan blade component untuk view list portfolio
> feat: add view component blade route list-portfolio

- resources/views/components/member-card.blade.php
- resources/views/components/pages/about-us.blade.php
- resources/views/components/pages/team-member.blade.php
merubah view component team member
> refactor: change component team member

- package-lock.json
- package.json
- resources/views/components/app-layout.blade.php
- resources/views/components/pages/list-portfolio.blade.php
- routes/web.php
update view pada list portfolio
> feat:add logic feature for filter tab; add mock route

- app/View/Components/Pages/AboutUs.php
- resources/views/components/pages/about-us.blade.php
- resources/views/welcome.blade.php
- routes/web.php
> feat: add view componen blade about us

- resources/views/components/pages/gallery.blade.php
menambahkan fitur modal ketika image diklik
> feat: add image clik to modal

- app/View/Components/Pages/Portfolio.php
- resources/views/components/pages/portfolio.blade.php
- routes/web.php
> feat: add portfolio page
